In [1]:
import numpy as np
import math
import iplantuml

### 3.2.6

```mermaid
stateDiagram-v2
    C-->M:0.2
    M-->C:0.3
    P-->M:0.7
    M-->P:0.6
    P-->C:0.1
    C-->P:0.2

```

In [2]:
A= np.array([[0.6, 0.2, 0.2],[0.3,0.1,0.6],[0.1,0.7,0.2]])
A

array([[0.6, 0.2, 0.2],
       [0.3, 0.1, 0.6],
       [0.1, 0.7, 0.2]])

In [3]:
# States after 2 years
result = A
for _ in range(1):
    result = result.dot(A)
np.diag(result)

array([0.44, 0.49, 0.48])

In [4]:
# States after 4 years
result = A
for _ in range(3):
    result = result.dot(A)
np.diag(result)

array([0.3504, 0.3709, 0.3668])

In [5]:
# States after 8 years
result = A
for _ in range(7):
    result = result.dot(A)
np.diag(result)

array([0.33377024, 0.33557629, 0.33521508])

In [6]:
### 4.4.2

In [21]:
r2=np.sqrt(1/2)
init = np.matrix([1,0,0,0])
qb=np.matrix([[0,r2,r2,0],[1j*r2,0,0,r2],[r2,0,0,1j*r2],[0,r2,-r2,0]])
qb

matrix([[ 0.        +0.j        ,  0.70710678+0.j        ,
          0.70710678+0.j        ,  0.        +0.j        ],
        [ 0.        +0.70710678j,  0.        +0.j        ,
          0.        +0.j        ,  0.70710678+0.j        ],
        [ 0.70710678+0.j        ,  0.        +0.j        ,
          0.        +0.j        ,  0.        +0.70710678j],
        [ 0.        +0.j        ,  0.70710678+0.j        ,
         -0.70710678+0.j        ,  0.        +0.j        ]])

In [23]:
qb@qb@qb@init.T

matrix([[ 0.        +0.j        ],
        [-0.70710678+0.70710678j],
        [ 0.        +0.j        ],
        [ 0.        +0.j        ]])